[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
lib_compat_mode = strict
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    https://github.com/ewowi/projectMM.git
    https://github.com/FastLED/FastLED.git

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
    -DWIFI_LOLIN_FIX
board_build.arduino.memory_type = qio_opi
