[platformio]
default_envs = esp32dev

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_compat_mode = strict
build_flags =
    -std=c++17
    -DBUILD_TARGET=\"$PIOENV\"
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    https://github.com/ewowi/projectMM.git#d500ffa74111bb2ee92f50553442e9e1cf9ffb0d ; R05 branch 20250424
    https://github.com/FastLED/FastLED.git
    bblanchon/ArduinoJson @ ^7
    ESP32Async/ESPAsyncWebServer#v3.10.3
board_build.filesystem = littlefs
board_build.littlefs_version = 2.0

[env:esp32dev]
board = esp32dev
board_build.arduino.partitions = partitions/esp32dev.csv

[env:esp32s3_n16r8]
board = esp32-s3-devkitc-1
build_flags =
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DWIFI_LOLIN_FIX
board_build.arduino.memory_type = qio_opi
board_build.arduino.partitions = partitions/esp32s3_n16r8.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
